/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ontology/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OntologyDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ontology/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OntologyDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssertionDto: {
            property?: string | null;
            propertyName?: string | null;
            value?: string | null;
            valueName?: string | null;
            datatype?: string | null;
            isObject?: boolean;
        };
        OntologyDto: {
            meta?: components["schemas"]["OntologyMeta"];
            classes?: components["schemas"]["OwlClassDto"][] | null;
            properties?: components["schemas"]["OwlPropertyDto"][] | null;
            individuals?: components["schemas"]["OwlIndividualDto"][] | null;
            stats?: components["schemas"]["StatsDto"];
        };
        OntologyMeta: {
            iri?: string | null;
            title?: string | null;
            comment?: string | null;
            sourceName?: string | null;
            imports?: string[] | null;
        };
        OwlClassDto: {
            id?: string | null;
            name?: string | null;
            label?: string | null;
            comment?: string | null;
            subClassOf?: string[] | null;
            disjointWith?: string[] | null;
            equivalentClasses?: string[] | null;
            restrictions?: components["schemas"]["RestrictionDto"][] | null;
            /** Format: int32 */
            instanceCount?: number;
            declared?: boolean;
        };
        OwlIndividualDto: {
            id?: string | null;
            name?: string | null;
            label?: string | null;
            comment?: string | null;
            types?: string[] | null;
            assertions?: components["schemas"]["AssertionDto"][] | null;
        };
        OwlPropertyDto: {
            id?: string | null;
            name?: string | null;
            label?: string | null;
            comment?: string | null;
            kind?: string | null;
            domains?: string[] | null;
            ranges?: string[] | null;
            inverseOf?: string | null;
            subPropertyOf?: string[] | null;
            characteristics?: string[] | null;
        };
        RestrictionDto: {
            onProperty?: string | null;
            onPropertyName?: string | null;
            kind?: string | null;
            filler?: string | null;
            fillerName?: string | null;
            /** Format: int32 */
            cardinality?: number | null;
            display?: string | null;
        };
        StatsDto: {
            /** Format: int32 */
            classes?: number;
            /** Format: int32 */
            objectProperties?: number;
            /** Format: int32 */
            datatypeProperties?: number;
            /** Format: int32 */
            annotationProperties?: number;
            /** Format: int32 */
            individuals?: number;
            /** Format: int32 */
            restrictions?: number;
            /** Format: int32 */
            disjointAxioms?: number;
            /** Format: int32 */
            subClassAxioms?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
